# Generated by Django 4.2.16 on 2024-10-18 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=50)),
                ('product_category_image', models.ImageField(blank=True, null=True, upload_to='product_category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sub_category_name', models.CharField(max_length=50)),
                ('product_sub_category_image', models.ImageField(blank=True, null=True, upload_to='product_sub_category')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecart.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='product_photos')),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_listing_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecart.productcategory')),
                ('product_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecart.productsubcategory')),
            ],
        ),
    ]
