# Generated by Django 4.2.16 on 2024-10-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Person_Name', models.CharField(max_length=150)),
                ('Contact_Person_phone_number', models.IntegerField(max_length=10)),
                ('Street_Address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
            ],
        ),
    ]
